version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    ports:
      - "8082:8082"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8081:8081"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
      hotel-service:
        condition: service_started

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - hotel-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_healthy
      booking-service:
        condition: service_started
      hotel-service:
        condition: service_started

networks:
  hotel-network:
    driver: bridge