spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    enable-termination-monitoring: true
    eviction-interval-timer-in-ms: 10000
    heartbeat-expires-after: 30
    renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8761